export const CardData = [
  {
    name: "SamSung",
    model: "samsung1312d",
    ram: "8GB Ram",
    rom: "64 GB Memory",
    camera: "20px",
    size: "6 inches",
    price: "RS 120000",
    src: "images/img1.jfif",
  },
  {
    name: "Huawei",
    model: "Huawei1345n",
    ram: "8GB Ram",
    rom: "64 GB Memory",
    camera: "20px",
    size: "6 inches",
    price: "RS 120000",
    src: "images/img2.jfif",
  },
  {
    name: "Oppo",
    model: "oppo2345j",
    ram: "8GB Ram",
    rom: "64 GB Memory",
    camera: "20px",
    size: "6 inches",
    price: "RS 120000",
    src: "images/img3.jfif",
  },
  {
    name: "SamSung",
    model: "samsung1312d",
    ram: "8GB Ram",
    rom: "64 GB Memory",
    camera: "20px",
    size: "6 inches",
    price: "RS 120000",
    src: "images/img1.jfif",
  },
  {
    name: "Huawei",
    model: "Huawei1345n",
    ram: "8GB Ram",
    rom: "64 GB Memory",
    camera: "20px",
    size: "6 inches",
    price: "RS 120000",
    src: "images/img2.jfif",
  },
  {
    name: "Oppo",
    model: "oppo2345j",
    ram: "8GB Ram",
    rom: "64 GB Memory",
    camera: "20px",
    size: "6 inches",
    price: "RS 120000",
    src: "images/img3.jfif",
  },
  {
    name: "Huawei",
    model: "Huawei1345n",
    ram: "8GB Ram",
    rom: "64 GB Memory",
    camera: "20px",
    size: "6 inches",
    price: "RS 120000",
    src: "images/img1.jfif",
  },
  {
    name: "SamSung",
    model: "samsung1312d",
    ram: "8GB Ram",
    rom: "64 GB Memory",
    camera: "20px",
    size: "6 inches",
    price: "RS 120000",
    src: "images/img2.jfif",
  },
  {
    name: "Oppo",
    model: "oppo2345j",
    ram: "8GB Ram",
    rom: "64 GB Memory",
    camera: "20px",
    size: "6 inches",
    price: "RS 120000",
    src: "images/img3.jfif",
  },
];
